#ifndef MQL_AUTO_FORWARDS_INCLUDED_DDF4BBE71DBD9685
#define MQL_AUTO_FORWARDS_INCLUDED_DDF4BBE71DBD9685
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/AGS/MT5/AGS.mq5


#endif
