#ifndef MQL_AUTO_FORWARDS_INCLUDED_1F1E1A1B19786061
#define MQL_AUTO_FORWARDS_INCLUDED_1F1E1A1B19786061
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/AGS/MT5/99_TestFramework/AGSConnectivityTest.mq5


#endif
