#ifndef MQL_AUTO_FORWARDS_INCLUDED_51E9A56B7D52987D
#define MQL_AUTO_FORWARDS_INCLUDED_51E9A56B7D52987D
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/AGS/MT5/99_TestFramework/AGSScenarioRunner.mq5

#line 50 "d:/Projects/AGS/MT5/99_TestFramework/AGSScenarioRunner.mq5"
int SessionStateNameToEnum(string name);
#line 61 "d:/Projects/AGS/MT5/99_TestFramework/AGSScenarioRunner.mq5"
string SessionStateEnumToName(int state);
#line 72 "d:/Projects/AGS/MT5/99_TestFramework/AGSScenarioRunner.mq5"
string XeStatusEnumToName(int status);
#line 100 "d:/Projects/AGS/MT5/99_TestFramework/AGSScenarioRunner.mq5"
void CloseAllChartsExceptCurrent();
#line 221 "d:/Projects/AGS/MT5/99_TestFramework/AGSScenarioRunner.mq5"
string ResolveSid(string actionSid);
#line 249 "d:/Projects/AGS/MT5/99_TestFramework/AGSScenarioRunner.mq5"
void HandleAction(CXTsdlAction* action);
#line 323 "d:/Projects/AGS/MT5/99_TestFramework/AGSScenarioRunner.mq5"
void VerifyExpectation(CXTsdlExpect* expect, int tick);
#line 410 "d:/Projects/AGS/MT5/99_TestFramework/AGSScenarioRunner.mq5"
void DebugLog(string msg);
#line 421 "d:/Projects/AGS/MT5/99_TestFramework/AGSScenarioRunner.mq5"
void ExecuteTick(int tick);

#endif
