#ifndef MQL_AUTO_FORWARDS_INCLUDED_C044A8659FCD29B1
#define MQL_AUTO_FORWARDS_INCLUDED_C044A8659FCD29B1
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/AGS/MT5/_Test/AGSScenarioRunner.mq5

#line 50 "d:/Projects/AGS/MT5/_Test/AGSScenarioRunner.mq5"
int SessionStateNameToEnum(string name);
#line 61 "d:/Projects/AGS/MT5/_Test/AGSScenarioRunner.mq5"
string SessionStateEnumToName(int state);
#line 72 "d:/Projects/AGS/MT5/_Test/AGSScenarioRunner.mq5"
string XeStatusEnumToName(int status);
#line 195 "d:/Projects/AGS/MT5/_Test/AGSScenarioRunner.mq5"
void HandleAction(CXTsdlAction* action);
#line 261 "d:/Projects/AGS/MT5/_Test/AGSScenarioRunner.mq5"
void VerifyExpectation(CXTsdlExpect* expect, int tick);
#line 353 "d:/Projects/AGS/MT5/_Test/AGSScenarioRunner.mq5"
void ExecuteTick(int tick);

#endif
