#ifndef MQL_AUTO_FORWARDS_INCLUDED_46F2C8CDA2361DBD
#define MQL_AUTO_FORWARDS_INCLUDED_46F2C8CDA2361DBD
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/AGS/MT5/_Test/AGSTestRunner.mq5


#endif
