#ifndef MQL_AUTO_FORWARDS_INCLUDED_D02FC8705DF06A73
#define MQL_AUTO_FORWARDS_INCLUDED_D02FC8705DF06A73
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/AGS/MT5/_Test/AGSTestRunner.mq5


#endif
