#ifndef MQL_AUTO_FORWARDS_INCLUDED_ECF2A6A005680340
#define MQL_AUTO_FORWARDS_INCLUDED_ECF2A6A005680340
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/AGS/MT5/99_TestFramework/AGSTestRunner.mq5

#line 35 "d:/Projects/AGS/MT5/99_TestFramework/AGSTestRunner.mq5"
include void CloseAllChartsExceptCurrent();

#endif
