#ifndef MQL_AUTO_FORWARDS_INCLUDED_E7601513E3A6FC45
#define MQL_AUTO_FORWARDS_INCLUDED_E7601513E3A6FC45
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/AGS/MT5/_Test/CXScenarioRunner.mq5

#line 49 "d:/Projects/AGS/MT5/_Test/CXScenarioRunner.mq5"
int SessionStateNameToEnum(string name);
#line 60 "d:/Projects/AGS/MT5/_Test/CXScenarioRunner.mq5"
string SessionStateEnumToName(int state);
#line 71 "d:/Projects/AGS/MT5/_Test/CXScenarioRunner.mq5"
string XeStatusEnumToName(int status);
#line 180 "d:/Projects/AGS/MT5/_Test/CXScenarioRunner.mq5"
void HandleAction(CXTsdlAction* action);
#line 246 "d:/Projects/AGS/MT5/_Test/CXScenarioRunner.mq5"
void VerifyExpectation(CXTsdlExpect* expect, int tick);
#line 338 "d:/Projects/AGS/MT5/_Test/CXScenarioRunner.mq5"
void ExecuteTick(int tick);

#endif
